// Furniture library — 178 items across 7 categories + presets

export const FURNITURE_LIBRARY = {
"des_sculpture": [
 { id: 'sculp-24-og', type: 'glb', name: 'osiris_rake_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/osirisrake-og-v126.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/rake1.png', description: 'TAGS: sculpture sculpture OG\n\nosiris rake (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/95', name: 'OpenSea' }] },
 { id: 'sculp-24-blck', type: 'glb', name: 'osiris_rake_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/osirisrake-dark-v124.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/rake2.png', description: 'TAGS: sculpture sculpture BLCK\n\nosiris rake (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/96', name: 'OpenSea' }] },
 { id: 'sculp-24-gry', type: 'glb', name: 'osiris_rake_GRY.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/osirisrake-light-v125.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/rake3.png', description: 'TAGS: sculpture sculpture GRY\n\nosiris rake (GRY).', tags: ['sculpture', 'sculpture', 'GRY'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/97', name: 'OpenSea' }] },
 { id: 'sculp-24-red', type: 'glb', name: 'osiris_rake_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/osirisrake-candle-v123.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/rake4.png', description: 'TAGS: sculpture sculpture RED\n\nosiris rake (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/98', name: 'OpenSea' }] },
 { id: 'sculp-25-og', type: 'glb', name: 'midas_space_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/midasspade-red-v114.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/spade1.png', description: 'TAGS: sculpture sculpture OG\n\nmidas space (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/99', name: 'OpenSea' }] },
 { id: 'sculp-25-dark', type: 'glb', name: 'midas_space_DARK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/midasspade-black-v111.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/spade2.png', description: 'TAGS: sculpture sculpture DARK\n\nmidas space (DARK).', tags: ['sculpture', 'sculpture', 'DARK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/100', name: 'OpenSea' }] },
 { id: 'sculp-25-light', type: 'glb', name: 'midas_space_LIGHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/midasspade-gray-v113.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/spade3.png', description: 'TAGS: sculpture sculpture LIGHT\n\nmidas space (LIGHT).', tags: ['sculpture', 'sculpture', 'LIGHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/101', name: 'OpenSea' }] },
 { id: 'sculp-25-candle', type: 'glb', name: 'midas_space_CANDLE.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/midasspade-gold-v112.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/spade4.png', description: 'TAGS: sculpture sculpture CANDLE\n\nmidas space (CANDLE).', tags: ['sculpture', 'sculpture', 'CANDLE'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/102', name: 'OpenSea' }] },
 { id: 'sculp-26-og', type: 'glb', name: 'angry_napkin_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/angry-napkin-og-v97.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/napkin-1.png', description: 'TAGS: sculpture sculpture OG\n\nangry napkin (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/103', name: 'OpenSea' }] },
 { id: 'sculp-26-blck', type: 'glb', name: 'angry_napkin_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/angry-napkin-mono2-blckmid-v96.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/napkin-2.png', description: 'TAGS: sculpture sculpture BLCK\n\nangry napkin (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/104', name: 'OpenSea' }] },
 { id: 'sculp-26-wht', type: 'glb', name: 'angry_napkin_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/angry-napkin-mono-v95.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/napkin-3.png', description: 'TAGS: sculpture sculpture WHT\n\nangry napkin (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/105', name: 'OpenSea' }] },
 { id: 'sculp-26-red', type: 'glb', name: 'angry_napkin_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/angry-napkin-red-v98.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/napkin-4.png', description: 'TAGS: sculpture sculpture RED\n\nangry napkin (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/106', name: 'OpenSea' }] },
 { id: 'sculp-27-og', type: 'glb', name: 'W6O1M6_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/w6o1m6-500K-v142.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/chemical-1.png', description: 'TAGS: sculpture sculpture OG\n\nW6O1M6 (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/107', name: 'OpenSea' }] },
 { id: 'sculp-27-blck', type: 'glb', name: 'W6O1M6_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/w6o1m6-500K_BLCK-v143.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/chemical-2.png', description: 'TAGS: sculpture sculpture BLCK\n\nW6O1M6 (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/108', name: 'OpenSea' }] },
 { id: 'sculp-27-gry', type: 'glb', name: 'W6O1M6_GRY.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/w6o1m6-500K_DARK-v144.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/chemical-3.png', description: 'TAGS: sculpture sculpture GRY\n\nW6O1M6 (GRY).', tags: ['sculpture', 'sculpture', 'GRY'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/109', name: 'OpenSea' }] },
 { id: 'sculp-27-red', type: 'glb', name: 'W6O1M6_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/w6o1m6-500K_RED-v145.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/chemical-4.png', description: 'TAGS: sculpture sculpture RED\n\nW6O1M6 (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/110', name: 'OpenSea' }] },
 { id: 'sculp-28-sohiii', type: 'glb', name: 'statue_of_hangover_SOHiii.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/soh-3-v137.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/hango-1.png', description: 'TAGS: sculpture sculpture SOHiii\n\nstatue of hangover (SOHiii).', tags: ['sculpture', 'sculpture', 'SOHiii'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/111', name: 'OpenSea' }] },
 { id: 'sculp-28-sohii', type: 'glb', name: 'statue_of_hangover_SOHii.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/soh-2-v136.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/hango-2.png', description: 'TAGS: sculpture sculpture SOHii\n\nstatue of hangover (SOHii).', tags: ['sculpture', 'sculpture', 'SOHii'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/112', name: 'OpenSea' }] },
 { id: 'sculp-28-sohi', type: 'glb', name: 'statue_of_hangover_SOHi.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/soh-1-v135.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/hango-3.png', description: 'TAGS: sculpture sculpture SOHi\n\nstatue of hangover (SOHi).', tags: ['sculpture', 'sculpture', 'SOHi'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/113', name: 'OpenSea' }] },
 { id: 'sculp-29-og', type: 'glb', name: 'praified_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/Praified-OG-v128.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/praified-1.png', description: 'TAGS: sculpture sculpture OG\n\npraified (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/114', name: 'OpenSea' }] },
 { id: 'sculp-29-blck', type: 'glb', name: 'praified_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/Praified-BLVK-v127.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/praified-2.png', description: 'TAGS: sculpture sculpture BLCK\n\npraified (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/115', name: 'OpenSea' }] },
 { id: 'sculp-29-wht', type: 'glb', name: 'praified_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/Praified-WHT-v130.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/praified-3.png', description: 'TAGS: sculpture sculpture WHT\n\npraified (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/116', name: 'OpenSea' }] },
 { id: 'sculp-29-red', type: 'glb', name: 'praified_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/Praified-RED-v129.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/praified-4.png', description: 'TAGS: sculpture sculpture RED\n\npraified (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/117', name: 'OpenSea' }] },
 { id: 'sculp-30-og', type: 'glb', name: 'sanctified_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/Sanctified-OG-v132.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/santified1.png', description: 'TAGS: sculpture sculpture OG\n\nsanctified (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/118', name: 'OpenSea' }] },
 { id: 'sculp-30-blck', type: 'glb', name: 'sanctified_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/Sanctified-BLCK-v131.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/santified2.png', description: 'TAGS: sculpture sculpture BLCK\n\nsanctified (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/119', name: 'OpenSea' }] },
 { id: 'sculp-30-wht', type: 'glb', name: 'sanctified_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/Sanctified-WHT-v134.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/santified3.png', description: 'TAGS: sculpture sculpture WHT\n\nsanctified (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/120', name: 'OpenSea' }] },
 { id: 'sculp-30-red', type: 'glb', name: 'sanctified_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/Sanctified-RED-v133.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/santified4.png', description: 'TAGS: sculpture sculpture RED\n\nsanctified (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/121', name: 'OpenSea' }] },
 { id: 'sculp-31-og', type: 'glb', name: 'me_tree_x_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/ME-TREE-X-og-v109.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/me-tree-x-1.png', description: 'TAGS: sculpture sculpture OG\n\nme-tree-x (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/122', name: 'OpenSea' }] },
 { id: 'sculp-31-blck', type: 'glb', name: 'me_tree_x_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/ME-TREE-X-blck-v107.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/me-tree-x-2.png', description: 'TAGS: sculpture sculpture BLCK\n\nme-tree-x (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/123', name: 'OpenSea' }] },
 { id: 'sculp-31-wht', type: 'glb', name: 'me_tree_x_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/ME-TREE-X-gry-v108.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/me-tree-x-3.png', description: 'TAGS: sculpture sculpture WHT\n\nme-tree-x (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/124', name: 'OpenSea' }] },
 { id: 'sculp-31-red', type: 'glb', name: 'me_tree_x_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/ME-TREE-X-red2-v110.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/me-tree-x-4.png', description: 'TAGS: sculpture sculpture RED\n\nme-tree-x (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/125', name: 'OpenSea' }] },
 { id: 'sculp-32-og', type: 'glb', name: 'molecular_data_plant_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/moleculardataplant-OG-v116.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/MOLECULAR-1.png', description: 'TAGS: sculpture sculpture OG\n\nmolecular data plant (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/126', name: 'OpenSea' }] },
 { id: 'sculp-32-blck', type: 'glb', name: 'molecular_data_plant_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/moleculardataplant-Blck-semiopaque-v115.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/MOLECULAR2.png', description: 'TAGS: sculpture sculpture BLCK\n\nmolecular data plant (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/127', name: 'OpenSea' }] },
 { id: 'sculp-32-wht', type: 'glb', name: 'molecular_data_plant_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/moleculardataplant-WHITE-v118.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/MOLECULAR3.png', description: 'TAGS: sculpture sculpture WHT\n\nmolecular data plant (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/128', name: 'OpenSea' }] },
 { id: 'sculp-32-red', type: 'glb', name: 'molecular_data_plant_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/moleculardataplant-Red-v117.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/MOLECULAR4.png', description: 'TAGS: sculpture sculpture RED\n\nmolecular data plant (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/129', name: 'OpenSea' }] },
 { id: 'sculp-33-og', type: 'glb', name: 'neo_klein_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/NEOKLEIN-og-v121.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/klein-1.png', description: 'TAGS: sculpture sculpture OG\n\nneo klein (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/130', name: 'OpenSea' }] },
 { id: 'sculp-33-blck', type: 'glb', name: 'neo_klein_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/NEOKLEIN-blck-v119.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/klein-2.png', description: 'TAGS: sculpture sculpture BLCK\n\nneo klein (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/131', name: 'OpenSea' }] },
 { id: 'sculp-33-gry', type: 'glb', name: 'neo_klein_GRY.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/NEOKLEIN-gry-v120.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/klein-3.png', description: 'TAGS: sculpture sculpture GRY\n\nneo klein (GRY).', tags: ['sculpture', 'sculpture', 'GRY'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/132', name: 'OpenSea' }] },
 { id: 'sculp-33-red', type: 'glb', name: 'neo_klein_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/NEOKLEIN-red2-v122.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/klein-4.png', description: 'TAGS: sculpture sculpture RED\n\nneo klein (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/133', name: 'OpenSea' }] },
 { id: 'sculp-34-og', type: 'glb', name: 'squiggle_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/chromiebridgeauralsection-OG-v140.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/SQUIGGLE1.png', description: 'TAGS: sculpture sculpture OG\n\nsquiggle (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/134', name: 'OpenSea' }] },
 { id: 'sculp-34-alien', type: 'glb', name: 'squiggle_ALIEN.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/chromiebridgeauralsection-alien3-v138.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/SQUIGGLE2.png', description: 'TAGS: sculpture sculpture ALIEN\n\nsquiggle (ALIEN).', tags: ['sculpture', 'sculpture', 'ALIEN'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/135', name: 'OpenSea' }] },
 { id: 'sculp-34-gry', type: 'glb', name: 'squiggle_GRY.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/chromiebridgeauralsection-gray2-v139.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/SQUIGGLE3.png', description: 'TAGS: sculpture sculpture GRY\n\nsquiggle (GRY).', tags: ['sculpture', 'sculpture', 'GRY'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/136', name: 'OpenSea' }] },
 { id: 'sculp-34-red', type: 'glb', name: 'squiggle_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/chromiebridgeauralsection-RED-v141.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/SQUIGGLE4.png', description: 'TAGS: sculpture sculpture RED\n\nsquiggle (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/137', name: 'OpenSea' }] },
 { id: 'sculp-35-og', type: 'glb', name: 'CROOKEDASWEFUNASYU_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/CROOKEDASWEFUNASYU-OG-v100.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/doge-1.png', description: 'TAGS: sculpture sculpture OG\n\nCROOKEDASWEFUNASYU (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/138', name: 'OpenSea' }] },
 { id: 'sculp-35-blck', type: 'glb', name: 'CROOKEDASWEFUNASYU_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/CROOKEDASWEFUNASYU-BLCK-v99.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/doge-2.png', description: 'TAGS: sculpture sculpture BLCK\n\nCROOKEDASWEFUNASYU (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/139', name: 'OpenSea' }] },
 { id: 'sculp-35-wht', type: 'glb', name: 'CROOKEDASWEFUNASYU_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/CROOKEDASWEFUNASYU-WHT-v102.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/doge-3.png', description: 'TAGS: sculpture sculpture WHT\n\nCROOKEDASWEFUNASYU (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/140', name: 'OpenSea' }] },
 { id: 'sculp-35-red', type: 'glb', name: 'CROOKEDASWEFUNASYU_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/CROOKEDASWEFUNASYU-RED-v101.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/doge-4.png', description: 'TAGS: sculpture sculpture RED\n\nCROOKEDASWEFUNASYU (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/141', name: 'OpenSea' }] },
 { id: 'sculp-36-og', type: 'glb', name: 'LEGEND_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/LEGEND-v103.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/legend-1.png', description: 'TAGS: sculpture sculpture OG\n\nLEGEND (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/142', name: 'OpenSea' }] },
 { id: 'sculp-36-blck', type: 'glb', name: 'LEGEND_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/LEGEND-BLCK-v104.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/legend-2.png', description: 'TAGS: sculpture sculpture BLCK\n\nLEGEND (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/143', name: 'OpenSea' }] },
 { id: 'sculp-36-wht', type: 'glb', name: 'LEGEND_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/LEGEND-CHRM-v105.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/legend-3.png', description: 'TAGS: sculpture sculpture WHT\n\nLEGEND (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/144', name: 'OpenSea' }] },
 { id: 'sculp-36-red', type: 'glb', name: 'LEGEND_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/LEGEND-RED-v106.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/legend-4.png', description: 'TAGS: sculpture sculpture RED\n\nLEGEND (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/145', name: 'OpenSea' }] },
 { id: 'sculp-37-og', type: 'glb', name: '2002_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/2002-OG-v92.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/2002-1.png', description: 'TAGS: sculpture sculpture OG\n\n2002 (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/146', name: 'OpenSea' }] },
 { id: 'sculp-37-blck', type: 'glb', name: '2002_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/2002-BLVKK-v91.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/2002-2.png', description: 'TAGS: sculpture sculpture BLCK\n\n2002 (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/147', name: 'OpenSea' }] },
 { id: 'sculp-37-tea', type: 'glb', name: '2002_TEA.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/2002-TEA-v93.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/2002-3.png', description: 'TAGS: sculpture sculpture TEA\n\n2002 (TEA).', tags: ['sculpture', 'sculpture', 'TEA'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/148', name: 'OpenSea' }] },
 { id: 'sculp-37-red', type: 'glb', name: '2002_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/2002-WHT-v94.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/2002-11.png', description: 'TAGS: sculpture sculpture RED\n\n2002 (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/149', name: 'OpenSea' }] },
 { id: 'sculp-38-og', type: 'glb', name: '0ff_with_his_head_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/0FF-og-v3.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/0FF-og.png', description: 'TAGS: sculpture sculpture OG\n\n0ff_with_his_head (OG).', tags: ['sculpture', 'sculpture', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/150', name: 'OpenSea' }] },
 { id: 'sculp-38-blck', type: 'glb', name: '0ff_with_his_head_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/0FF-BLCK-v4.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/0FF-blck.png', description: 'TAGS: sculpture sculpture BLCK\n\n0ff_with_his_head (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/151', name: 'OpenSea' }] },
 { id: 'sculp-38-wht', type: 'glb', name: '0ff_with_his_head_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/0FF-WHT-v1.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/0FF-wht.png', description: 'TAGS: sculpture sculpture WHT\n\n0ff_with_his_head (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/152', name: 'OpenSea' }] },
 { id: 'sculp-38-red', type: 'glb', name: '0ff_with_his_head_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/0FF-Red-v2.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/0FF-red.png', description: 'TAGS: sculpture sculpture RED\n\n0ff_with_his_head (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/153', name: 'OpenSea' }] },
 { id: 'sculp-39-mix', type: 'glb', name: 'mysticalarcases_MIX.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/mystical-arcases-mix2-v1.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/MYSTCARCASES--MİX2.png', description: 'TAGS: sculpture sculpture MIX\n\nmysticalarcases (MIX).', tags: ['sculpture', 'sculpture', 'MIX'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/157', name: 'OpenSea' }] },
 { id: 'sculp-39-blck', type: 'glb', name: 'mysticalarcases_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/mystical-arcases-blck-v147.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/mystical-1.png', description: 'TAGS: sculpture sculpture BLCK\n\nmysticalarcases (BLCK).', tags: ['sculpture', 'sculpture', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/155', name: 'OpenSea' }] },
 { id: 'sculp-39-wht', type: 'glb', name: 'mysticalarcases_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/mystical-arcases-wht-v148.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/MYSTCARCASES-WHT.png', description: 'TAGS: sculpture sculpture WHT\n\nmysticalarcases (WHT).', tags: ['sculpture', 'sculpture', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/156', name: 'OpenSea' }] },
 { id: 'sculp-39-red', type: 'glb', name: 'mysticalarcases_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/mystical-arcases-red-v146.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/mystical-2.png', description: 'TAGS: sculpture sculpture RED\n\nmysticalarcases (RED).', tags: ['sculpture', 'sculpture', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/154', name: 'OpenSea' }] }
],
 "des_automobile": [
 { id: 'auto-40-og-red', type: 'glb', name: 'XYZ008_OG-red.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XYZ008-red-v4.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XYZ008-red.png', description: 'TAGS: automobile automobile OG -red\n\nXYZ008 (OG -red).', tags: ['automobile', 'automobile', 'OG -red'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/160', name: 'OpenSea' }] },
 { id: 'auto-40-blck', type: 'glb', name: 'XYZ008_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XYZ008-blck-v1.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XYZ008-blck-og.png', description: 'TAGS: automobile automobile BLCK\n\nXYZ008 (BLCK).', tags: ['automobile', 'automobile', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/158', name: 'OpenSea' }] },
 { id: 'auto-40-glss', type: 'glb', name: 'XYZ008_GLSS.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XYZ008-glasser-v2.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XYZ008-glasser.png', description: 'TAGS: automobile automobile GLSS\n\nXYZ008 (GLSS).', tags: ['automobile', 'automobile', 'GLSS'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/159', name: 'OpenSea' }] },
 { id: 'auto-40-gold', type: 'glb', name: 'XYZ008_GOLD.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XYZ008-golds-v3.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XYZ008-gold.png', description: 'TAGS: automobile automobile GOLD\n\nXYZ008 (GOLD).', tags: ['automobile', 'automobile', 'GOLD'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/161', name: 'OpenSea' }] },
 { id: 'auto-40-yllw', type: 'glb', name: 'XYZ008_YLLW.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XYZ008-yellow-v5.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XYZ008-yellow.png', description: 'TAGS: automobile automobile YLLW\n\nXYZ008 (YLLW).', tags: ['automobile', 'automobile', 'YLLW'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/162', name: 'OpenSea' }] },
 { id: 'auto-41-og', type: 'glb', name: 'zenbubble_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/ZBR-OG2-v7.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/zbr-og.png', description: 'TAGS: automobile automobile OG\n\nzenbubble (OG).', tags: ['automobile', 'automobile', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/163', name: 'OpenSea' }] },
 { id: 'auto-41-villain', type: 'glb', name: 'zenbubble_VILLAIN.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/ZBR-BLCKK-v6.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/zbr-blck.png', description: 'TAGS: automobile automobile VILLAIN\n\nzenbubble (VILLAIN).', tags: ['automobile', 'automobile', 'VILLAIN'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/164', name: 'OpenSea' }] },
 { id: 'auto-41-wht', type: 'glb', name: 'zenbubble_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/ZBR-WHT-v9.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/zbwht.png', description: 'TAGS: automobile automobile WHT\n\nzenbubble (WHT).', tags: ['automobile', 'automobile', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/165', name: 'OpenSea' }] },
 { id: 'auto-41-red', type: 'glb', name: 'zenbubble_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/ZBR-RED-v8.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/zbr-red.png', description: 'TAGS: automobile automobile RED\n\nzenbubble (RED).', tags: ['automobile', 'automobile', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/166', name: 'OpenSea' }] },
 { id: 'auto-42-og', type: 'glb', name: 'skewer_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/skewer-og2-v16.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/skewers-OG.png', description: 'TAGS: automobile automobile OG\n\nskewer (OG).', tags: ['automobile', 'automobile', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/167', name: 'OpenSea' }] },
 { id: 'auto-42-blck', type: 'glb', name: 'skewer_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/skewer-blck-v17.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/skewers-BLCK.png', description: 'TAGS: automobile automobile BLCK\n\nskewer (BLCK).', tags: ['automobile', 'automobile', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/168', name: 'OpenSea' }] },
 { id: 'auto-42-wht', type: 'glb', name: 'skewer_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/skewer-wht2-v14.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/skewers-WHT.png', description: 'TAGS: automobile automobile WHT\n\nskewer (WHT).', tags: ['automobile', 'automobile', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/169', name: 'OpenSea' }] },
 { id: 'auto-42-red', type: 'glb', name: 'skewer_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/skewer-red-v15.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/skewers-RED.png', description: 'TAGS: automobile automobile RED\n\nskewer (RED).', tags: ['automobile', 'automobile', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/170', name: 'OpenSea' }] },
 { id: 'auto-43-og', type: 'glb', name: 'wellington_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/wellngton-og-v11.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/WELLINGTON-OG.png', description: 'TAGS: automobile automobile OG\n\nwellington (OG).', tags: ['automobile', 'automobile', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/171', name: 'OpenSea' }] },
 { id: 'auto-43-blck', type: 'glb', name: 'wellington_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/wellngton-blck-v10.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/WELLINGTON-BLCK.png', description: 'TAGS: automobile automobile BLCK\n\nwellington (BLCK).', tags: ['automobile', 'automobile', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/172', name: 'OpenSea' }] },
 { id: 'auto-43-wht', type: 'glb', name: 'wellington_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/wellngton-wht-v13.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/WELLINGTON-WHT.png', description: 'TAGS: automobile automobile WHT\n\nwellington (WHT).', tags: ['automobile', 'automobile', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/173', name: 'OpenSea' }] },
 { id: 'auto-43-red', type: 'glb', name: 'wellington_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/wellngton-red-v12.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/WELLINGTON-RED.png', description: 'TAGS: automobile automobile RED\n\nwellington (RED).', tags: ['automobile', 'automobile', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/174', name: 'OpenSea' }] },
 { id: 'auto-44-og', type: 'glb', name: 'MarsDEADLeaf_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XXX-MarsDEADLeaf-BLUPINKPURP-v19.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XXX-MarsDEADLeaf-BLUPINKPURP-og.png', description: 'TAGS: automobile automobile OG\n\nMarsDEADLeaf (OG).', tags: ['automobile', 'automobile', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/175', name: 'OpenSea' }] },
 { id: 'auto-44-blck', type: 'glb', name: 'MarsDEADLeaf_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XXX-MarsDEADLeaf-BLCK-v18.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XXX-MarsDEADLeaf-BLCK.png', description: 'TAGS: automobile automobile BLCK\n\nMarsDEADLeaf (BLCK).', tags: ['automobile', 'automobile', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/176', name: 'OpenSea' }] },
 { id: 'auto-44-wht', type: 'glb', name: 'MarsDEADLeaf_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XXX-MarsDEADLeaf-WHT-v21.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XXX-MarsDEADLeaf-WHT.png', description: 'TAGS: automobile automobile WHT\n\nMarsDEADLeaf (WHT).', tags: ['automobile', 'automobile', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/177', name: 'OpenSea' }] },
 { id: 'auto-44-neon', type: 'glb', name: 'MarsDEADLeaf_NEON.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/XXX-MarsDEADLeaf-NEON2-v20.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/XXX-MarsDEADLeaf-neon.png', description: 'TAGS: automobile automobile NEON\n\nMarsDEADLeaf (NEON).', tags: ['automobile', 'automobile', 'NEON'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/178', name: 'OpenSea' }] }
],
"des_chair": [
 { id: 'chair-1-og', type: 'glb', name: 'mermaidchair_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/mermaid-chair-og-v2.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/mermaidchair-og.png', description: 'TAGS: furniture chair OG\n\nmermaidchair (OG).', tags: ['furniture', 'chair', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/1', name: 'OpenSea' }] },
 { id: 'chair-1-blck', type: 'glb', name: 'mermaidchair_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/mermaid-chair-black-v4.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/mermaidchair-b.png', description: 'TAGS: furniture chair BLCK\n\nmermaidchair (BLCK).', tags: ['furniture', 'chair', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/2', name: 'OpenSea' }] },
 { id: 'chair-1-chrome', type: 'glb', name: 'mermaidchair_CHROME.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/mermaid-chair-chrome-v1.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/mermaidchair-w.png', description: 'TAGS: furniture chair CHROME\n\nmermaidchair (CHROME).', tags: ['furniture', 'chair', 'CHROME'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/3', name: 'OpenSea' }] },
 { id: 'chair-1-red', type: 'glb', name: 'mermaidchair_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/mermaid-chair-red-v3.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/mermaidchair-red.png', description: 'TAGS: furniture chair RED\n\nmermaidchair (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/4', name: 'OpenSea' }] },
 { id: 'chair-2-og', type: 'glb', name: 'fetuchair_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/fetuchair-OG.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/fetuchair-og.png', description: 'TAGS: furniture chair OG\n\nfetuchair (OG).', tags: ['furniture', 'chair', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/5', name: 'OpenSea' }] },
 { id: 'chair-2-blck', type: 'glb', name: 'fetuchair_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/fetuchair-blck.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/fetuchair-bü,.png', description: 'TAGS: furniture chair BLCK\n\nfetuchair (BLCK).', tags: ['furniture', 'chair', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/6', name: 'OpenSea' }] },
 { id: 'chair-2-wht', type: 'glb', name: 'fetuchair_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/fetuchair-white.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/fetuchair-w.png', description: 'TAGS: furniture chair WHT\n\nfetuchair (WHT).', tags: ['furniture', 'chair', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/7', name: 'OpenSea' }] },
 { id: 'chair-2-red', type: 'glb', name: 'fetuchair_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/fetuchair-red.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/fetuchair-red.png', description: 'TAGS: furniture chair RED\n\nfetuchair (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/8', name: 'OpenSea' }] },
 { id: 'chair-3-antrst', type: 'glb', name: 'dse_ANTRST.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DSE-antst-v5.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dse-og.png', description: 'TAGS: furniture chair ANTRST\n\ndse (ANTRST).', tags: ['furniture', 'chair', 'ANTRST'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/9', name: 'OpenSea' }] },
 { id: 'chair-3-blck', type: 'glb', name: 'dse_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DSE-black-v6.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dse-b.png', description: 'TAGS: furniture chair BLCK\n\ndse (BLCK).', tags: ['furniture', 'chair', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/10', name: 'OpenSea' }] },
 { id: 'chair-3-wht', type: 'glb', name: 'dse_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DSE-white-v8.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dse-delix.png', description: 'TAGS: furniture chair WHT\n\ndse (WHT).', tags: ['furniture', 'chair', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/11', name: 'OpenSea' }] },
 { id: 'chair-3-red', type: 'glb', name: 'dse_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DSE-red-v7.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dse-red.png', description: 'TAGS: furniture chair RED\n\ndse (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/12', name: 'OpenSea' }] },
 { id: 'chair-4-og', type: 'glb', name: 'jackthelad_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/jack-the-lad-xx-OG-v9.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/jacktehladxx-og.png', description: 'TAGS: furniture chair OG\n\njackthelad (OG).', tags: ['furniture', 'chair', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/13', name: 'OpenSea' }] },
 { id: 'chair-4-blck', type: 'glb', name: 'jackthelad_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/jack-the-lad-xx-blck-v12.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/jacktehladxx-b.png', description: 'TAGS: furniture chair BLCK\n\njackthelad (BLCK).', tags: ['furniture', 'chair', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/14', name: 'OpenSea' }] },
 { id: 'chair-4-wht', type: 'glb', name: 'jackthelad_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/jack-the-lad-xx-wht-v11.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/jacktehladxx-w.png', description: 'TAGS: furniture chair WHT\n\njackthelad (WHT).', tags: ['furniture', 'chair', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/15', name: 'OpenSea' }] },
 { id: 'chair-4-red', type: 'glb', name: 'jackthelad_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/jack-the-lad-xx-red-v10.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/jacktehladxx-red.png', description: 'TAGS: furniture chair RED\n\njackthelad (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/16', name: 'OpenSea' }] },
 { id: 'chair-5-antrst', type: 'glb', name: 'aretaix_ANTRST.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/aretaix-OG-v14.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/aretaix-og.png', description: 'TAGS: furniture chair ANTRST\n\naretaix (ANTRST).', tags: ['furniture', 'chair', 'ANTRST'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/17', name: 'OpenSea' }] },
 { id: 'chair-5-blck', type: 'glb', name: 'aretaix_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/aretaix-black-v13.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/aretaix-b.png', description: 'TAGS: furniture chair BLCK\n\naretaix (BLCK).', tags: ['furniture', 'chair', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/18', name: 'OpenSea' }] },
 { id: 'chair-5-wht', type: 'glb', name: 'aretaix_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/aretaix-WHT-v16.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/aretaix-w.png', description: 'TAGS: furniture chair WHT\n\naretaix (WHT).', tags: ['furniture', 'chair', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/19', name: 'OpenSea' }] },
 { id: 'chair-5-red', type: 'glb', name: 'aretaix_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/aretaix-red-v15.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/aretaix-red.png', description: 'TAGS: furniture chair RED\n\naretaix (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/20', name: 'OpenSea' }] },
 { id: 'chair-6-og', type: 'glb', name: 'armageddon_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/armageddonseat-v17.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/armageddon-og.png', description: 'TAGS: furniture chair OG\n\narmageddon (OG).', tags: ['furniture', 'chair', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/21', name: 'OpenSea' }] },
 { id: 'chair-6-blck', type: 'glb', name: 'armageddon_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/armageddon-black-v19.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/armageddon-b.png', description: 'TAGS: furniture chair BLCK\n\narmageddon (BLCK).', tags: ['furniture', 'chair', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/22', name: 'OpenSea' }] },
 { id: 'chair-6-wht', type: 'glb', name: 'armageddon_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/armageddon-antrst-v18.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/armageddon-w.png', description: 'TAGS: furniture chair WHT\n\narmageddon (WHT).', tags: ['furniture', 'chair', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/23', name: 'OpenSea' }] },
 { id: 'chair-6-dark', type: 'glb', name: 'armageddon_DARK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/armageddon-red-v20.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/armageddon-red.png', description: 'TAGS: furniture chair DARK\n\narmageddon (DARK).', tags: ['furniture', 'chair', 'DARK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/24', name: 'OpenSea' }] },
 { id: 'chair-7-chrome', type: 'glb', name: 'bilbao_lego_chair_CHROME.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/bilbao-lego-chair-v21.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/bilbaolego-og.png', description: 'TAGS: furniture chair CHROME\n\nbilbao lego chair (CHROME).', tags: ['furniture', 'chair', 'CHROME'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/25', name: 'OpenSea' }] },
 { id: 'chair-7-blck', type: 'glb', name: 'bilbao_lego_chair_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/bilbao-lego-chair-black-v22.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/bilbaolego-b.png', description: 'TAGS: furniture chair BLCK\n\nbilbao lego chair (BLCK).', tags: ['furniture', 'chair', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/26', name: 'OpenSea' }] },
 { id: 'chair-7-wht', type: 'glb', name: 'bilbao_lego_chair_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/bilbao-lego-chair-white-v24.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/bilbaolego-w.png', description: 'TAGS: furniture chair WHT\n\nbilbao lego chair (WHT).', tags: ['furniture', 'chair', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/27', name: 'OpenSea' }] },
 { id: 'chair-7-red', type: 'glb', name: 'bilbao_lego_chair_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/bilbao-lego-chair-dark-v23.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/bilbaolego-neon.png', description: 'TAGS: furniture chair RED\n\nbilbao lego chair (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/28', name: 'OpenSea' }] },
 { id: 'chair-8-chrome', type: 'glb', name: 'higgs_boson_CHROME.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/higgs-boson-chrome-r-v25.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/higgsboson-og.png', description: 'TAGS: furniture chair CHROME\n\nhiggs boson (CHROME).', tags: ['furniture', 'chair', 'CHROME'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/29', name: 'OpenSea' }] },
 { id: 'chair-8-night', type: 'glb', name: 'higgs_boson_NIGHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/higgs-boson-night-r-v27.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/higgsboson-darkblue.png', description: 'TAGS: furniture chair NIGHT\n\nhiggs boson (NIGHT).', tags: ['furniture', 'chair', 'NIGHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/30', name: 'OpenSea' }] },
 { id: 'chair-8-concrete', type: 'glb', name: 'higgs_boson_CONCRETE.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/higgs-boson-concrete-r-v26.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/higgsboson-w.png', description: 'TAGS: furniture chair CONCRETE\n\nhiggs boson (CONCRETE).', tags: ['furniture', 'chair', 'CONCRETE'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/31', name: 'OpenSea' }] },
 { id: 'chair-8-red', type: 'glb', name: 'higgs_boson_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/higgs-boson-red-r-v28.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/higgsboson-red.png', description: 'TAGS: furniture chair RED\n\nhiggs boson (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/32', name: 'OpenSea' }] },
 { id: 'chair-9-og', type: 'glb', name: 'e66_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/E66-chair-v31.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/e66-og.png', description: 'TAGS: furniture chair OG\n\ne66 (OG).', tags: ['furniture', 'chair', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/33', name: 'OpenSea' }] },
 { id: 'chair-9-blck', type: 'glb', name: 'e66_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/e66-blck-v30.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/e66-b.png', description: 'TAGS: furniture chair BLCK\n\ne66 (BLCK).', tags: ['furniture', 'chair', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/34', name: 'OpenSea' }] },
 { id: 'chair-9-antrst', type: 'glb', name: 'e66_ANTRST.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/e66-antrst-v29.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/e66-w.png', description: 'TAGS: furniture chair ANTRST\n\ne66 (ANTRST).', tags: ['furniture', 'chair', 'ANTRST'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/35', name: 'OpenSea' }] },
 { id: 'chair-9-red', type: 'glb', name: 'e66_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/e66-red-v32.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/e66-red.png', description: 'TAGS: furniture chair RED\n\ne66 (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/36', name: 'OpenSea' }] },
 { id: 'chair-10-og', type: 'glb', name: 'Accelerator_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/angry-chair-OG-v35.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/angrynapkin-og.png', description: 'TAGS: furniture chair OG\n\nAccelerator (OG).', tags: ['furniture', 'chair', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/37', name: 'OpenSea' }] },
 { id: 'chair-10-mono', type: 'glb', name: 'Accelerator_MONO.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/angry-chair-mono-v34.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/angrynapkin-mono.png', description: 'TAGS: furniture chair MONO\n\nAccelerator (MONO).', tags: ['furniture', 'chair', 'MONO'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/38', name: 'OpenSea' }] },
 { id: 'chair-10-davnc', type: 'glb', name: 'Accelerator_DAVNC.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/angry-chair-dvnc-v33.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/angrynapkin-danvc.png', description: 'TAGS: furniture chair DAVNC\n\nAccelerator (DAVNC).', tags: ['furniture', 'chair', 'DAVNC'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/39', name: 'OpenSea' }] },
 { id: 'chair-10-red', type: 'glb', name: 'Accelerator_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/angry-chair-red-v36.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/angrynapkin-red.png', description: 'TAGS: furniture chair RED\n\nAccelerator (RED).', tags: ['furniture', 'chair', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/40', name: 'OpenSea' }] }
],
"des_sofa": [
 { id: 'sofa-11-og', type: 'glb', name: 'glass_gougnut_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/GlassDougnutCommunicationUnit-gry-v59.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dougnut-og.png', description: 'TAGS: furniture sofa OG\n\nglass gougnut (OG).', tags: ['furniture', 'sofa', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/41', name: 'OpenSea' }] },
 { id: 'sofa-11-blck', type: 'glb', name: 'glass_gougnut_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/GlassDougnutCommunicationUnit-blck-v58.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dougnut-blck.png', description: 'TAGS: furniture sofa BLCK\n\nglass gougnut (BLCK).', tags: ['furniture', 'sofa', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/42', name: 'OpenSea' }] },
 { id: 'sofa-11-wht', type: 'glb', name: 'glass_gougnut_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/GlassDougnutCommunicationUnit-wht-v61.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dougnut-w.png', description: 'TAGS: furniture sofa WHT\n\nglass gougnut (WHT).', tags: ['furniture', 'sofa', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/43', name: 'OpenSea' }] },
 { id: 'sofa-11-red', type: 'glb', name: 'glass_gougnut_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/GlassDougnutCommunicationUnit-red-v60.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dougnut-red.png', description: 'TAGS: furniture sofa RED\n\nglass gougnut (RED).', tags: ['furniture', 'sofa', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/44', name: 'OpenSea' }] },
 { id: 'sofa-12-og', type: 'glb', name: 'sjsoc_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/sjsoc-gry-v66.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/sjsoc-og.png', description: 'TAGS: furniture sofa OG\n\nsjsoc (OG).', tags: ['furniture', 'sofa', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/45', name: 'OpenSea' }] },
 { id: 'sofa-12-mono', type: 'glb', name: 'sjsoc_MONO.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/sjsoc-monoc-v67.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/sjsoc-b.png', description: 'TAGS: furniture sofa MONO\n\nsjsoc (MONO).', tags: ['furniture', 'sofa', 'MONO'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/46', name: 'OpenSea' }] },
 { id: 'sofa-12-wht', type: 'glb', name: 'sjsoc_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/sjsoc-wht-v69.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/sjsoc-w.png', description: 'TAGS: furniture sofa WHT\n\nsjsoc (WHT).', tags: ['furniture', 'sofa', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/47', name: 'OpenSea' }] },
 { id: 'sofa-12-neon', type: 'glb', name: 'sjsoc_NEON.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/sjsoc-neon-v68.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/sjsoc-red.png', description: 'TAGS: furniture sofa NEON\n\nsjsoc (NEON).', tags: ['furniture', 'sofa', 'NEON'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/48', name: 'OpenSea' }] },
 { id: 'sofa-13-og', type: 'glb', name: 'carwrecksofa_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/carwrecksofa-gray-v55.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/carwreck-og.png', description: 'TAGS: furniture sofa OG\n\ncarwrecksofa (OG).', tags: ['furniture', 'sofa', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/49', name: 'OpenSea' }] },
 { id: 'sofa-13-blck', type: 'glb', name: 'carwrecksofa_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/carwrecksofa-black-v54.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/carwreck-b.png', description: 'TAGS: furniture sofa BLCK\n\ncarwrecksofa (BLCK).', tags: ['furniture', 'sofa', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/50', name: 'OpenSea' }] },
 { id: 'sofa-13-wht', type: 'glb', name: 'carwrecksofa_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/carwrecksofa-white-v57.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/carwreck-w.png', description: 'TAGS: furniture sofa WHT\n\ncarwrecksofa (WHT).', tags: ['furniture', 'sofa', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/51', name: 'OpenSea' }] },
 { id: 'sofa-13-red', type: 'glb', name: 'carwrecksofa_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/carwrecksofa-red-v56.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/carwreck-red.png', description: 'TAGS: furniture sofa RED\n\ncarwrecksofa (RED).', tags: ['furniture', 'sofa', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/52', name: 'OpenSea' }] },
 { id: 'sofa-14-og', type: 'glb', name: 'Japon_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/-sofa-v64.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/japon-og.png', description: 'TAGS: furniture sofa OG\n\n冬 (Japon) (OG).', tags: ['furniture', 'sofa', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/53', name: 'OpenSea' }] },
 { id: 'sofa-14-blck', type: 'glb', name: 'Japon_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/-blck-v62.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/japon-b.png', description: 'TAGS: furniture sofa BLCK\n\n冬 (Japon) (BLCK).', tags: ['furniture', 'sofa', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/54', name: 'OpenSea' }] },
 { id: 'sofa-14-wht', type: 'glb', name: 'Japon_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/-white-v65.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/japon-w.png', description: 'TAGS: furniture sofa WHT\n\n冬 (Japon) (WHT).', tags: ['furniture', 'sofa', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/55', name: 'OpenSea' }] },
 { id: 'sofa-14-red', type: 'glb', name: 'Japon_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/-red-v63.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/japon-red.png', description: 'TAGS: furniture sofa RED\n\n冬 (Japon) (RED).', tags: ['furniture', 'sofa', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/56', name: 'OpenSea' }] }
],
"des_table": [
 { id: 'table-15-og', type: 'glb', name: '2070S_DJ_TABLE_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/2070s-dj-table-HANDBAKE-v71.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/2070sdjtable-og.png', description: 'TAGS: furniture table OG\n\n2070S DJ TABLE (OG).', tags: ['furniture', 'table', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/57', name: 'OpenSea' }] },
 { id: 'table-15-blck', type: 'glb', name: '2070S_DJ_TABLE_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/2070s-dj-table-BLCK-v70.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/2070sdjtable-b.png', description: 'TAGS: furniture table BLCK\n\n2070S DJ TABLE (BLCK).', tags: ['furniture', 'table', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/58', name: 'OpenSea' }] },
 { id: 'table-15-wht', type: 'glb', name: '2070S_DJ_TABLE_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/2070s-dj-table-WHT-v73.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/2070sdjtable-w.png', description: 'TAGS: furniture table WHT\n\n2070S DJ TABLE (WHT).', tags: ['furniture', 'table', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/59', name: 'OpenSea' }] },
 { id: 'table-15-red', type: 'glb', name: '2070S_DJ_TABLE_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/2070s-dj-table-RED2-v72.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/2070sdjtable-red.png', description: 'TAGS: furniture table RED\n\n2070S DJ TABLE (RED).', tags: ['furniture', 'table', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/60', name: 'OpenSea' }] },
 { id: 'table-16-og', type: 'glb', name: 'BoardROOMTABLE_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BoardROOMTABLE-OG-v75.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/agressiveboardmeetingunit-og.png', description: 'TAGS: furniture table OG\n\nBoardROOMTABLE (OG).', tags: ['furniture', 'table', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/61', name: 'OpenSea' }] },
 { id: 'table-16-blck', type: 'glb', name: 'BoardROOMTABLE_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BoardROOMTABLE-BLCK-v74.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/agressiveboardmeetingunit-b.png', description: 'TAGS: furniture table BLCK\n\nBoardROOMTABLE (BLCK).', tags: ['furniture', 'table', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/62', name: 'OpenSea' }] },
 { id: 'table-16-wht', type: 'glb', name: 'BoardROOMTABLE_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BoardROOMTABLE-WHT-v77.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/agressiveboardmeetingunit-w.png', description: 'TAGS: furniture table WHT\n\nBoardROOMTABLE (WHT).', tags: ['furniture', 'table', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/63', name: 'OpenSea' }] },
 { id: 'table-16-red', type: 'glb', name: 'BoardROOMTABLE_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BoardROOMTABLE-RED-v76.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/agressiveboardmeetingunit-red.png', description: 'TAGS: furniture table RED\n\nBoardROOMTABLE (RED).', tags: ['furniture', 'table', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/64', name: 'OpenSea' }] },
 { id: 'table-16-glss', type: 'glb', name: 'BoardROOMTABLE_GLSS.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BoardROOMTABLE-GLASS-v78.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/tekli-glass-aggressive.png', description: 'TAGS: furniture table GLSS\n\nBoardROOMTABLE (GLSS).', tags: ['furniture', 'table', 'GLSS'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/65', name: 'OpenSea' }] },
 { id: 'table-17-og', type: 'glb', name: 'BrownSharkTable_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BROWNSHARTABLE-OG-v82.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/brownsharktable-og.png', description: 'TAGS: furniture table OG\n\nBrown Shark Table (OG).', tags: ['furniture', 'table', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/66', name: 'OpenSea' }] },
 { id: 'table-17-dark', type: 'glb', name: 'BrownSharkTable_DARK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BROWNSHARTABLE-DARK-v79.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/brownsharktable-black.png', description: 'TAGS: furniture table DARK\n\nBrown Shark Table (DARK).', tags: ['furniture', 'table', 'DARK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/67', name: 'OpenSea' }] },
 { id: 'table-17-rock', type: 'glb', name: 'BrownSharkTable_ROCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BROWNSHARTABLE-ROCK-v81.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/brownsharktable-rock.png', description: 'TAGS: furniture table ROCK\n\nBrown Shark Table (ROCK).', tags: ['furniture', 'table', 'ROCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/68', name: 'OpenSea' }] },
 { id: 'table-17-red', type: 'glb', name: 'BrownSharkTable_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/BROWNSHARTABLE-RED-v80.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/brownsharktable-red.png', description: 'TAGS: furniture table RED\n\nBrown Shark Table (RED).', tags: ['furniture', 'table', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/69', name: 'OpenSea' }] }
],
"des_music": [
 { id: 'music-18-og', type: 'glb', name: 'decentrlizejoking1_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJSET-OG-v38.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/djset1-og.png', description: 'TAGS: furniture music OG\n\ndecentrlize*joking1 (OG).', tags: ['furniture', 'music', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/70', name: 'OpenSea' }] },
 { id: 'music-18-blck', type: 'glb', name: 'decentrlizejoking1_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJSET-BLCK-v37.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/djset1-b.png', description: 'TAGS: furniture music BLCK\n\ndecentrlize*joking1 (BLCK).', tags: ['furniture', 'music', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/71', name: 'OpenSea' }] },
 { id: 'music-18-wht', type: 'glb', name: 'decentrlizejoking1_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJSET-WHITE-v41.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/djset1-w.png', description: 'TAGS: furniture music WHT\n\ndecentrlize*joking1 (WHT).', tags: ['furniture', 'music', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/72', name: 'OpenSea' }] },
 { id: 'music-18-red', type: 'glb', name: 'decentrlizejoking1_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJSET-RED-v39.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/djset1-red.png', description: 'TAGS: furniture music RED\n\ndecentrlize*joking1 (RED).', tags: ['furniture', 'music', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/73', name: 'OpenSea' }] },
 { id: 'music-18-retro', type: 'glb', name: 'decentrlizejoking1_Retro.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJSET-RETRO-v40.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj1-5-retro.png', description: 'TAGS: furniture music Retro\n\ndecentrlize*joking1 (Retro).', tags: ['furniture', 'music', 'Retro'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/74', name: 'OpenSea' }] },
 { id: 'music-19-og', type: 'glb', name: 'decentrlizejoking2_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/dj2-BLACK-OG-v44.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj2-og.png', description: 'TAGS: furniture music OG\n\ndecentrlize*joking2_offroad (OG).', tags: ['furniture', 'music', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/75', name: 'OpenSea' }] },
 { id: 'music-19-gry', type: 'glb', name: 'decentrlizejoking2_GRY.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/dj2-GRY-v42.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj2-mono.png', description: 'TAGS: furniture music GRY\n\ndecentrlize*joking2_offroad (GRY).', tags: ['furniture', 'music', 'GRY'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/76', name: 'OpenSea' }] },
 { id: 'music-19-wht', type: 'glb', name: 'decentrlizejoking2_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/dj2-WHT-v45.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj2-w.png', description: 'TAGS: furniture music WHT\n\ndecentrlize*joking2_offroad (WHT).', tags: ['furniture', 'music', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/77', name: 'OpenSea' }] },
 { id: 'music-19-red', type: 'glb', name: 'decentrlizejoking2_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/dj2-RED-v43.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj2-red.png', description: 'TAGS: furniture music RED\n\ndecentrlize*joking2_offroad (RED).', tags: ['furniture', 'music', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/78', name: 'OpenSea' }] },
 { id: 'music-20-og', type: 'glb', name: 'decentrlizejoking2_2_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJ2_2_og-GRY-v47.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj2-2-og.png', description: 'TAGS: furniture music OG\n\ndecentrlize*joking2_2 (OG).', tags: ['furniture', 'music', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/79', name: 'OpenSea' }] },
 { id: 'music-20-blck', type: 'glb', name: 'decentrlizejoking2_2_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJ2_2_BLACK-v46.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj2-2-b.png', description: 'TAGS: furniture music BLCK\n\ndecentrlize*joking2_2 (BLCK).', tags: ['furniture', 'music', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/80', name: 'OpenSea' }] },
 { id: 'music-20-wht', type: 'glb', name: 'decentrlizejoking2_2_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJ2_2_wakara-wht2-v49.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj2-2-w.png', description: 'TAGS: furniture music WHT\n\ndecentrlize*joking2_2 (WHT).', tags: ['furniture', 'music', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/81', name: 'OpenSea' }] },
 { id: 'music-20-red', type: 'glb', name: 'decentrlizejoking2_2_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/DJ2_2_red-V2-v48.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/dj2-2-red.png', description: 'TAGS: furniture music RED\n\ndecentrlize*joking2_2 (RED).', tags: ['furniture', 'music', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/82', name: 'OpenSea' }] },
 { id: 'music-21-og', type: 'glb', name: 'screamer_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/SCREAMER-OG-GRY-v53.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/screamer-og.png', description: 'TAGS: furniture music OG\n\nscreamer (OG).', tags: ['furniture', 'music', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/83', name: 'OpenSea' }] },
 { id: 'music-21-blck', type: 'glb', name: 'screamer_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/SCREAMER-BLCK-v52.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/screamer-b.png', description: 'TAGS: furniture music BLCK\n\nscreamer (BLCK).', tags: ['furniture', 'music', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/84', name: 'OpenSea' }] },
 { id: 'music-21-wht', type: 'glb', name: 'screamer_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/SCREAMER-WHT-v51.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/screamer-w.png', description: 'TAGS: furniture music WHT\n\nscreamer (WHT).', tags: ['furniture', 'music', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/85', name: 'OpenSea' }] },
 { id: 'music-21-red', type: 'glb', name: 'screamer_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/SCREAMER-RED-v50.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/screamer-red.png', description: 'TAGS: furniture music RED\n\nscreamer (RED).', tags: ['furniture', 'music', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/86', name: 'OpenSea' }] }
],
"des_carpet": [
 { id: 'carpet-22-og', type: 'glb', name: 'genetic_carpet_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/merged-GRY-og-v84.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/genetic-og.png', description: 'TAGS: furniture carpet OG\n\ngenetic carpet (OG).', tags: ['furniture', 'carpet', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/87', name: 'OpenSea' }] },
 { id: 'carpet-22-blck', type: 'glb', name: 'genetic_carpet_BLCK.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/merged-blck-v83.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/genetic-b.png', description: 'TAGS: furniture carpet BLCK\n\ngenetic carpet (BLCK).', tags: ['furniture', 'carpet', 'BLCK'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/88', name: 'OpenSea' }] },
 { id: 'carpet-22-wht', type: 'glb', name: 'genetic_carpet_WHT.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/merged-WHT-v86.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/genetic-w.png', description: 'TAGS: furniture carpet WHT\n\ngenetic carpet (WHT).', tags: ['furniture', 'carpet', 'WHT'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/89', name: 'OpenSea' }] },
 { id: 'carpet-22-red', type: 'glb', name: 'genetic_carpet_RED.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/merged-red-v85.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/genetic-r.png', description: 'TAGS: furniture carpet RED\n\ngenetic carpet (RED).', tags: ['furniture', 'carpet', 'RED'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/90', name: 'OpenSea' }] },
 { id: 'carpet-23-og', type: 'glb', name: 'spooky_carpet_OG.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/spooky-verdealip-carpet-v90.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/spookycarpet-verdialpi.png', description: 'TAGS: furniture carpet OG\n\nspooky carpet (OG).', tags: ['furniture', 'carpet', 'OG'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/91', name: 'OpenSea' }] },
 { id: 'carpet-23-blackigator', type: 'glb', name: 'spooky_carpet_BLACKIGATOR.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/spooky-blackigator-carpet-v87.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/spookycarpet-leather.png', description: 'TAGS: furniture carpet BLACKIGATOR\n\nspooky carpet (BLACKIGATOR).', tags: ['furniture', 'carpet', 'BLACKIGATOR'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/92', name: 'OpenSea' }] },
 { id: 'carpet-23-throne', type: 'glb', name: 'spooky_carpet_THRONE.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/spooky-throne-carpet-3-v89.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/spookycarpet-wtdbts.png', description: 'TAGS: furniture carpet THRONE\n\nspooky carpet (THRONE).', tags: ['furniture', 'carpet', 'THRONE'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/93', name: 'OpenSea' }] },
 { id: 'carpet-23-davnc', type: 'glb', name: 'spooky_carpet_DAVNC.glb', url: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign/main/spooky-davinci-carpet-v88.glb', thumbnailUrl: 'https://raw.githubusercontent.com/decentralize-dfw/dfwdesign-thumb/main/spookycarpet-davnc.png', description: 'TAGS: furniture carpet DAVNC\n\nspooky carpet (DAVNC).', tags: ['furniture', 'carpet', 'DAVNC'], links: [{ url: 'https://opensea.io/item/base/0xa7e1c80c850af5cfb8ae709daa3b968d685fde5f/94', name: 'OpenSea' }] }
]
};

/** Return all items as a flat array */
export function getAllItems() {
  return Object.values(FURNITURE_LIBRARY).flat();
}

/** Return items for a given category key (e.g. "des_chair") */
export function getItemsByCategory(cat) {
  return FURNITURE_LIBRARY[cat] || [];
}

/** Return the list of category keys */
export function getCategories() {
  return Object.keys(FURNITURE_LIBRARY);
}

// ============================================================
// PRESETS — Ready-made furniture sets (single GLB per preset)
// Each preset is a complete room setup loaded as one model.
// Tags allow filtering by room/area for future multi-room presets.
// ============================================================

export const FURNITURE_PRESETS = [
  {
    id: 'full-house-v2',
    name: 'Tüm Ev (Mobilyalı)',
    url: 'https://raw.githubusercontent.com/decentralize-dfw/vea-randomfiles/main/empty-house-furniture-opt-v2.glb',
    tags: ['tüm-ev', 'salon', 'mutfak', 'yatak-odası-1', 'yatak-odası-2', 'banyo', 'wc'],
    description: 'Tüm odalar mobilyalı — salon, mutfak, yatak odaları, banyo, WC'
  }
];

/** Return all presets */
export function getAllPresets() {
  return FURNITURE_PRESETS;
}

/** Return presets matching a tag (e.g. 'salon', 'mutfak') */
export function getPresetsByTag(tag) {
  return FURNITURE_PRESETS.filter(p => p.tags.includes(tag));
}

/** Return all unique preset tags */
export function getPresetTags() {
  const tags = new Set();
  for (const p of FURNITURE_PRESETS) p.tags.forEach(t => tags.add(t));
  return [...tags];
}
